#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:KrCksUGWifATW4bB6EYQlA==,iv:YwGa7tl8F/p6rfyH64gB84mQlYU3MEPFOzLxLnX6cAE=,tag:CLyb3r+h39xtjj/8xfdkUQ==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:0hQKQU0JWFGKbie+fEzuJleFwWd+hDCS,iv:UpYzDNWVpp1ENchTVtpt35R+vj5k91gjhkPo7cXJNXU=,tag:JZUAY6bpHBsLWpkWNgDhFw==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:cC4BlmCJyDBKweEagxuvmoHuyi8O5wnupOz3qOGPcUC8X/+Udzz8AcL5kVe6Yyqa+dPHRpfoQf8Px+8aeBeDMKhAiGGpyVCngnnoQAf9QAJbCPdlilDhPiwrSBFKzpCh/YUh/bN/sOFfpXFbrhj3WBu9a82GkMKWjbWABc+DL435eZxE,iv:HPfVYOR3/E2TNfzRK0EaFJ5fCKoV+zd/iUQBKWsRj/4=,tag:mu6diRW4jvELFbkQ2W0emA==,type:str]
    GE_SERVER_DATABASE_USER: ENC[AES256_GCM,data:/OJ8E8L59qi/TEm2JFgGQyLeysdbEkZqpGf6ng==,iv:GBsR2w9bdMMKH/f6RAwi7rnfgOFGwkDN/SHnT497rOY=,tag:bhX290kHhlzCGUDbG34xdw==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:zn/svwcOUpLosYY85ZqlfL6AZbIj740Nf341YsDpQ5BQTXieNmeE6JbpsTo=,iv:h0PJ5Ff/MqGpBQZy0jMASMRWNYmG7NCNzxntMmO+FgI=,tag:i+qqokaWWScaFtsADcg0Fw==,type:str]
    GE_AUTH_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:4YJRdYTNveU5I96TzoRwoRWeb5lI+ulRVhNHpDVWf0Qo9o85uoQiL/lYZzw=,iv:xr8nLN4KDIwlvx16tKNpKOESg5IiHOJFDa7p1Y7drec=,tag:Vm0Ks900nim3XuHd+k9dcg==,type:str]
    GE_AUTH_KEYCLOAK_REALM_PUBLIC_KEY: ENC[AES256_GCM,data:fNFgG7SeN6ckuqSKSIIYyi/G+T6+tgyJHk7lNCRoCBPfrw/AjYPOfGPLHbWGJH/de5EZ9lpA89wxVmaKejkOYx2AqSywnMNVL7WHHDQ/NgDBp2wV93PoTyF31kezgtRETxEC8fu/hW3QS0AQzFC/OhTmflIfcqkbQPo7Px9YwqUPHuWB4665SeMyHg2LlQlj0z40l4jLn8ykCNd1uZmrQiq3hJdL1vuhdYcanb1x3mzE365PpiRoI26jAgY3YxFLGGRH2SbrarfJHrRxGWB03g3zG6Kf7t4UlpHb2Ml+M7yKs6NaYoAXFgOj1uHBUpmIOn6ey1K/p46p9NuEkxLUH0ctXELvMvXVgYaoWiFiSaC4ItV+suTbBdDtFXsaS6TEEUP6h4YFBMQpFZVTfpG48nZBiwHA0Z1bdcxSf47SKS38AqH8FbxsKodWUkJmGjqqhak2c0xzu+r8D2zAsEfhRjfKNaonuo3Vwu2zsm9q9Jlac8GQbewqZaAFZsxkiH4VtLW9s3BmL+vx5Wb2cbcC3zSHNV2XSGPkbZvfq/ShqEJHKFI/5K+FF4GqZ4cTZ8frBHGTXjNZrXKx3jTD/xaLCWwmB7HGWgXM1STe1GgFKraN6U1MpV291xZnDXMmaRzCKL2JS2HQ/UI5niby01IxVCbqkgROb1FYg/2xO9Qi+aDhLZCbm7MU0rsLKJM=,iv:8XZyeauKGJMwRoh+nLmplSPg6saX5cTKAqi5DO9bRO0=,tag:qZ0YQ2kTJfFL/ZpC1y8t0Q==,type:str]
    GE_AUTH_KEYCLOAK_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:EdJ31SBss3jvJrE5iKaLQW9lCtXFBRQzWqlwqdlYnYKeRAUourPmig0e1PU=,iv:kS+UgtEiEMIqn3FFkaW75dW6iBiqJzZHIlhTCo7IoZc=,tag:HPVSO1Xv63xpje5Td5Ia7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-21T18:35:34Z"
    mac: ENC[AES256_GCM,data:zNU/Gre83V2azFMypDHZyP9f/PVB7RHUcFs46virFy73rX4ok2yEVdVjjy5UTy2KgaE1N1phbvQzxiNg8OE/FGluNvtNNMj6XNZg24LWNWL65AyX9SELW3wbjsTsMdNp87p7ea9fKD+ynOVmzVjcppohZB7kInUzfUBIqxJHMTU=,iv:g2PB+uE607+VSEDu1EPBGrWoRup7qZSIj65oxSuGlwM=,tag:7W04uEhhbLEGeNFy+Teg0w==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
