services:
  mongo:
    image: mongo
    restart: always
    command: [mongod, --bind_ip_all, --port, "27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: root
      DB_PASS: example
      DB_NAME: green-space-management
      PORT: 3000
