#ENC[AES256_GCM,data:IKXsSNuQ7/b5jxaV57BXS3efJdKFOsiDGsjpx0/b8qDgcz4ko3Mf58gRKTWx1PrxR03ptAWnrwPtmw==,iv:HRBcGmHpMTso+lF3Ko/Q0268VAF6IomwxcusyqP7mr8=,tag:QnjLLquZvJ9jsrsIDk4gqA==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: mongo-express-secrets
type: Opaque
data:
    ME_CONFIG_MONGODB_ADMINUSERNAME: ENC[AES256_GCM,data:N9mm41rwNPAzXRuXrmxD6mO/v9aDXQJL81NGguKf4Qmx6si/W5dXpQ==,iv:yVsvIZK6Dy1YGej8SfpizDrY7KYCC8VSYbrHdeep1Rw=,tag:C3FkMgH9ImE/1OtfSINiHQ==,type:str]
    ME_CONFIG_MONGODB_ADMINPASSWORD: ENC[AES256_GCM,data:el7a7GG9InVDnNlzVHwm+a+0IqyKsQmDYofn34azAGUBRPSoxvOK7QVuSnw=,iv:6EiEnE4w2G2AntnmLByOee6b1pRQ4BtYBh3l/raECps=,tag:Pu6N+QFkaSl2AEJAPwrb9w==,type:str]
    ME_CONFIG_MONGODB_URL: ENC[AES256_GCM,data:iKEGXRQskenrA7yX3WDOr8fRayC3QTsgboO2jBDXzMS22LxKFHImdmcRsmAMshs8oQqjxGdmxG52FuVTZeHeaTyLHW679+F6w9axhwD1gEoX0Qo4dL7jz3jEjqklowUeAHbmlGW52fOvMXrA4njmeTZJPd8UgykOfFiY0opfuY0=,iv:jHNv/D5nlo9qlBlffOJeDV7TK3pNUnkr8nDrYpbHovc=,tag:uwZ0ORRktP3IkDULSy1wsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SkVldXgwVDd0eFNqd2Vx
            a05nYWM3MmJzREw1eVlKZDhwVW82U1oya0RJCnBOSElUQ3NqTGtGaFhtWlE1L3kw
            RVY2b2xVR1ZKa1FraHRpcGN1WEpld00KLS0tIFFTYXg0V0xOckRKNGZvRWpOYWhC
            YWtQQWZlWkM5Slo5c2hHU2ZWVS8vRHMKFuOEwEk6Qr/jg4kI2fMTk0ydwlLWi0OG
            AWWW2mgkeoVl7UDOE/9+oev0r4A7er0of9YuUE52Eb1DkryfGvm0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T22:15:57Z"
    mac: ENC[AES256_GCM,data:O37pBd5w9n6tDo2/zO/IVRmYuyT2JuLubGc3QS2g4W8/nMiq/jFzZDoXuqbRdCvx7rEx5PhfKyhPq6x6yzNPCx/j1SmKwBa2UPvs19gGlB3Vojz4VhBxHDehyJ0gwcYbqPFpUyVyEeLwPzFXR3BY6AMSJYrDTQFwGcJhOh5hAwk=,iv:51PW2M6Jaw392lolSDL4wZPgsS39B0bmb7nGQ4FgAaw=,tag:lyy3usBLK1biEfkxyWTbzA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
---
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SkVldXgwVDd0eFNqd2Vx
            a05nYWM3MmJzREw1eVlKZDhwVW82U1oya0RJCnBOSElUQ3NqTGtGaFhtWlE1L3kw
            RVY2b2xVR1ZKa1FraHRpcGN1WEpld00KLS0tIFFTYXg0V0xOckRKNGZvRWpOYWhC
            YWtQQWZlWkM5Slo5c2hHU2ZWVS8vRHMKFuOEwEk6Qr/jg4kI2fMTk0ydwlLWi0OG
            AWWW2mgkeoVl7UDOE/9+oev0r4A7er0of9YuUE52Eb1DkryfGvm0gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-27T22:15:57Z"
    mac: ENC[AES256_GCM,data:O37pBd5w9n6tDo2/zO/IVRmYuyT2JuLubGc3QS2g4W8/nMiq/jFzZDoXuqbRdCvx7rEx5PhfKyhPq6x6yzNPCx/j1SmKwBa2UPvs19gGlB3Vojz4VhBxHDehyJ0gwcYbqPFpUyVyEeLwPzFXR3BY6AMSJYrDTQFwGcJhOh5hAwk=,iv:51PW2M6Jaw392lolSDL4wZPgsS39B0bmb7nGQ4FgAaw=,tag:lyy3usBLK1biEfkxyWTbzA==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
