# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  ports:
  - name: mongo-express
    protocol: TCP
    port: 80
    targetPort: 8081
---

