#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:KrCksUGWifATW4bB6EYQlA==,iv:YwGa7tl8F/p6rfyH64gB84mQlYU3MEPFOzLxLnX6cAE=,tag:CLyb3r+h39xtjj/8xfdkUQ==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:0hQKQU0JWFGKbie+fEzuJleFwWd+hDCS,iv:UpYzDNWVpp1ENchTVtpt35R+vj5k91gjhkPo7cXJNXU=,tag:JZUAY6bpHBsLWpkWNgDhFw==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:cC4BlmCJyDBKweEagxuvmoHuyi8O5wnupOz3qOGPcUC8X/+Udzz8AcL5kVe6Yyqa+dPHRpfoQf8Px+8aeBeDMKhAiGGpyVCngnnoQAf9QAJbCPdlilDhPiwrSBFKzpCh/YUh/bN/sOFfpXFbrhj3WBu9a82GkMKWjbWABc+DL435eZxE,iv:HPfVYOR3/E2TNfzRK0EaFJ5fCKoV+zd/iUQBKWsRj/4=,tag:mu6diRW4jvELFbkQ2W0emA==,type:str]
    GE_SERVER_DATABASE_USER: ENC[AES256_GCM,data:QM3qhg/V8a3OojPm5q9b/F9slOnkEue+aIKy2w==,iv:OTxGLopfP9aYbmvFwsv7vM2cMcz4HGhWazUCmZIPeHc=,tag:e8k2OdB0jkeCqgnGo259YQ==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:TG3bRbbXicqTAHVO6ieJHfnHR8i1f5s7OgqweK21ZGGNnCI+NSz/F18n8p8=,iv:iN0QcisvUYKX3O6ohCfoR0Dh2E4AT8TSiqIlJhr7o58=,tag:c3vNncoKQLN3XXpEdIHpnA==,type:str]
    GE_AUTH_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:Xd3MF4NLPc6fwMgdw8fL3A9F3EkUGNOxJOksH2eezB/Ry3edCTy//pQlUrg=,iv:ayfOhrvTVG5PgFWhdOCb7tzcFKsQ70SiyEGoGmRV1p4=,tag:iAk+1pbgIeS3r3fg3Q+rVw==,type:str]
    GE_AUTH_KEYCLOAK_REALM_PUBLIC_KEY: ENC[AES256_GCM,data:CTlirO+nswhNvBxhaeEn7skIaX7PZUbO2h0q7xbZg0hkYAv9Mx+Viz1j+KBlOGr3PCJCthf/+/+UQ3SROJgfLD/SeIT2ljlZfvohY2trFLCeviV5KEt1XkgZnImN9gn5Ft/axPEfNqf+2HBds7wLkjo1H2nIuJEJXMSHdkpXtXkDP7l8K4ixHN0j3WdHF8w3HBN0aXOFqbdm+1IR0HZRlQBqxGI4FgZV2H5LbNaC615Y++5EJPqLdiEp2p2LLTVd9k2Xx94VkJR4U+CDZjoHOpfSNIJyTnKv34a95on2s2IZDfPbLbBOnVu8RtgqGai+SsdcHfK7D9gXByEObgEj/rEADXnAiKwi5jQBFS5v+VDo+NiXWlZuiyUwaN+6FJ/Jd+aZYsbjuG5XECdONc/Sy30HVjYuTvkGbnBrMXkuaEnS06yUCLmEl1i6RMlcBbqD8M9tapUB+u9NHD9U1XF18cdbY+98HXv3Y42nq6P3zSpInLHyJXKdZDmp+g5GWsQLupIS9s6hKcgE4/CNudzU4d8Mp8lrbaVxMK+J3uzQe8knSq3T47lIKaJeZTgfHL3zU2/OdVpzWVelllcN5+zGU7hcolVcxu+0Q3XmV7LLaxhtr7B5o3LxoL66G0nEJNBpQbH9DuEpYd+IEqbZczu9jf/HfuTaeRB2Icv92yYeQc/UJ0+ym6c0Y3ypDvA=,iv:ZYNPvFET6F/fcq1sW42JmHdjtLbF3o9d3rKkI0YFtWc=,tag:h00Nd1JzzGGtmwUvyXGR6Q==,type:str]
    GE_AUTH_KEYCLOAK_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:0j2HQUM8sMKASXzWcLTdly3rOCXS+QZI3+zZIa5SxXEKXLzy3OIbjVX/AGc=,iv:ptATKyZATI+d/kS4O91lV/eRURqg7CS4Eh6x2OuS0zc=,tag:dIABof7zP1GFnuNluqca1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-14T15:45:16Z"
    mac: ENC[AES256_GCM,data:e+f/bBCGoQtR7iT0qa+qWG2ymfrSNjMmosR58bDY4cRRxZjHH7nq+CJf51mXiSC3oe94ZzW/5g1KdMWW1hEOVZUMRR/UYNqamrIfwS2aelZ35y/8Ot19+adKETHOt7PFrn98Hmd39kmBvzCGcnW3jScA5tswWg3wgdMHAbJRxtY=,iv:QvhxcImLdObsXZs6NhQxWcMjoStMNCtL5PRIFV+uzGk=,tag:b8T2dLaXe6OwDVbM5lYgxQ==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.1
