# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  ME_CONFIG_BASICAUTH: "false"
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
---

