# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo
  type: ClusterIP
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
---

