apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - ../base/backend
  - ../base/frontend
images:
  - name: frontend-image
    newName: ghcr.io/green-ecolution/green-ecolution-frontend-dev
    newTag: afa6209
  - name: backend-image
    newName: ghcr.io/green-ecolution/green-ecolution-backend-dev
    newTag: 5242e5d
  - name: init-migrations-image
    newName: ghcr.io/green-ecolution/migrations-postgres
    newTag: latest
generators:
  - ./secret-generator.yaml
patches:
  - path: config.yaml
  - path: backend-deployment.yaml
