#ENC[AES256_GCM,data:prx6D9V57yjlTpXthhUyqk9Kt2GTIiC3E/N6j+9LVOZwu9AcMZV3uyiiijOPblnTbsqOCR8eVdobRQ==,iv:s6m8m8wT9nwDRl0h5FH9ARPMvAykGiEqq81w/+YzTnM=,tag:phf1fM10RcFTiHQH+XnAuQ==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:KrCksUGWifATW4bB6EYQlA==,iv:YwGa7tl8F/p6rfyH64gB84mQlYU3MEPFOzLxLnX6cAE=,tag:CLyb3r+h39xtjj/8xfdkUQ==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:0hQKQU0JWFGKbie+fEzuJleFwWd+hDCS,iv:UpYzDNWVpp1ENchTVtpt35R+vj5k91gjhkPo7cXJNXU=,tag:JZUAY6bpHBsLWpkWNgDhFw==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:cC4BlmCJyDBKweEagxuvmoHuyi8O5wnupOz3qOGPcUC8X/+Udzz8AcL5kVe6Yyqa+dPHRpfoQf8Px+8aeBeDMKhAiGGpyVCngnnoQAf9QAJbCPdlilDhPiwrSBFKzpCh/YUh/bN/sOFfpXFbrhj3WBu9a82GkMKWjbWABc+DL435eZxE,iv:HPfVYOR3/E2TNfzRK0EaFJ5fCKoV+zd/iUQBKWsRj/4=,tag:mu6diRW4jvELFbkQ2W0emA==,type:str]
    GE_SERVER_DATABASE_USER: ENC[AES256_GCM,data:kRTyNMYr75vDbOrN80ElPK0Q4fAX5xt1CrJgrg==,iv:sJNltBdsDvWUSSHhLGlpM00IQJpi3qixHMSsvVHMp0o=,tag:qwnHi3RJV4XxEkDGob+bSQ==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:7eD/vS8D3zD1whFHpSeAnuOTUhYbtKPQocw4ZNCOsuzmNM8EViDRVr16+nY=,iv:1yp1Zm7W+WsPD9TIxvGuEhHZw/e/WJRR0CXm/++TOlY=,tag:dRyZ1k5O67A8VoYGirUfBA==,type:str]
    GE_AUTH_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:jkocOQby73yDnJfhuGyO461SJD25t7PoG4j/EGOT9x52zhspKEVhhIIOPOI=,iv:bkTVwTAehNI7cC9w7+m8bloF9AsaJeDWna67rhVcA+Q=,tag:hjdTBTKlHigCA1JzZXlb5Q==,type:str]
    GE_AUTH_KEYCLOAK_REALM_PUBLIC_KEY: ENC[AES256_GCM,data:jP46Yrot84buT9Twfc8Jv6jDgBYy5oPJQtoR9xHVcVSC4TAiXPnV/NwonY5DiwqPPtNzyhnXjD3AWZramQn//MjXpXFvDYXIeCFOA+h/hFIib/yegyvyk8e60rSdObNLitUvjPHImj78ajHYOLsdJGP1oXfP3yO1BYrhqqThTMSLi6dHbKQ33IA28YjYp9DzoolSOotlbn2IY53ThmOO7BlY3KyuZEPJZpX+n3yKbeTwAPn0M+cRvr66169UErcYbZmX5cMbR3DYnD7yHvoHHQjDXRG/rOlbDq4J/DM2R9tNnKPCh3Th5sedcmiqOauH0VYJxJ1g0zO9vSV9PQGtOohzkwI5BKEOyk3JntzKLWqqj1F03b3HJOgyD8kQcQEfqs9F68O8SMhOwKi41fkjKT7ixU1QUYWkzJWQVBR/qPtMASerStbDsyTsrytbbdWWE++x5ByQdoqBsKfsf9EltAJZXyVuLJh62o9+z8pILRa3eY/fjOBHFTVpbX+/TfQ7KvYGkoJuWFR1Ao4w+61zlByDNpZz16nH4Lzqc1ZXdOdml5U+qvwj1FWmk7w5zFRat4U/rzt/lAcUeg2hH7LeBllARhWuPc0nsnbe7PjVszIk0PRnQEDPBtFbwp0E8VMNQXAfzKErtzJZAbGeHC09+LVUjHmWGM30QoR8oenWIF2Ze1Q8oroeBIvHVkU=,iv:Y2Rb1Y/CghIvdoh/UGAvhrL/G6jylQUDfosHaVn6cvw=,tag:4jPYrDKCRzKiOs1G2UFN9g==,type:str]
    GE_AUTH_KEYCLOAK_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:dOGSN7+W6b2wJvdPpu+VPVKemX8GJ+tGGZZGs48xulx56YDa68dQJCbLFR0=,iv:EvinBlu0Go7kCTBs3b/WK4a8gvLqGgEl95Wf4i9O2Sw=,tag:S7ffAvxSCgXDTQJmYC0j2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicUdXME5xQnhyTUZSRWhW
            NjJLZmRNQlZ1NDVDL0M2eWYvaTUrbHpTVkZnCmdyOHYyUE55a1l0eUp2cVFvQXYr
            dnZEVlpSWUVuYUlkSnFqeTVxZWgrWUEKLS0tIGsrKzVxMEdBM2hKUTA2Y25Hc0Fm
            RDBzNVZoWE45d3hac2FmVWRxWk5Ka0EKvntxf0hTY68ZFVVGfuPTfNPL++lOyOcD
            qJr9VXQltbuKpKZYe272PDe7lb7wdxt1bbxEOPvQW/IdBnvSM3Kx/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T23:28:18Z"
    mac: ENC[AES256_GCM,data:9fzzIY9zJalii4M/XO5SYtVCdDkrflo1KGo7hMh/9O3omEKpr2UYF753/kJb/a/ednHYZ5HpQmAjjzs/vv2b7Pi75miv0J4G0WJfrypA+cGvs0dBiMyKTdahg7z/dvASVlRifvMy3rSPnYnQNrTTYE6AkhD1V88EZ8bXSMlUwSQ=,iv:biNsLNJlRKSFaKEdgoNLErZWdVtj6DbFM93eM+9R2B8=,tag:a7G2+bs/RnkNRNwOLRiSZg==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
