#ENC[AES256_GCM,data:LcFhXmtsy0f3KTipZy+KQZex6K1O6cnP3xwqt7ZFnAHBAtLtM1TSjAJUr+Kx5N2scSiTWTq32G8ing==,iv:37GfyPH2mjho6JcLXnzXRidTkR7o3eWx/Xc4ZljFVOo=,tag:04HIWQ3dZYYl1bjWkv7u7g==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    MQTT_CLIENT_ID: ENC[AES256_GCM,data:+91XNNXos3Xch15sYO/7NQ==,iv:8cc7I92lgkU32dD1qTIP2KGSwWaD+myzyoGqeKx5lzc=,tag:+vn3u6y0Uvqyzvox1ziNxQ==,type:str]
    MQTT_USERNAME: ENC[AES256_GCM,data:sENzYkVPsqoeHnUBhw2uX7BSFLbGo8C4,iv:k7KdagUb4vmsUf1S9xNmu9egTeja9yTtvvBGDYaLbrY=,tag:MHzj7H8bopmrzCxGGkS3Og==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:E3qshhoPVOs9CJWxAAjF5Kx5pNNHZi1acEkqswGwswG8Ox8HiqLXkuI+A5Xai+f3+Hjr/1nV089x9ILKQVIJsUdPISbXLYpVQ37YLlXI2xqBtye6B7PBPmg0GkaALeyy580fOIuosy5Q/hgfROn1BNAr553K43MBmTLsjOBq+cdHeNoR,iv:EOwHF9iIy7/jCEk3/ggXqV0Ec5Q1o+SCRozUw/9CBiU=,tag:h5F7GKDiF06/jJ6x7Zwyqw==,type:str]
    DB_USER: ENC[AES256_GCM,data:uxs80Li7HwddNtXxluOLLn698cjWxZaFMQFQSRLof8BrPiL3NfI17Q==,iv:W5E4AQ7o7QnHzZKLCGc46jPUsfjHT1zYIDYtgNLy8VI=,tag:u1jli86ryMTOJc9tWSqInw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:558PLVudeeKD91ZCtm+hBmlKFt6TPgVHfcemud45hH9/NyD5hvLo62pQ/R8=,iv:sc3+FVKafE9x8qkzTSuqZKh27I3xZUULBii4VL4AYpM=,tag:i07FC/mR2UzZfRozKh0Jig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaHhCTDFmZ01XbHpweDlD
            NGJuNUVBNnhmeEJybjM2Njl4TjJSbW9NK3owClJNOVQrTWZ6SmF1cUUyeHE3UmMz
            b2NKMU9pTjJGblRxd0RtTUJmVmF2T0kKLS0tIDFSMDJVeEkxd3RGeEhTa1dwUXdy
            aVBVaGpZUXZnckNBWEhjVHdUNjZiMkUKZS/lGhzdoKoL9X5Bwn4fD8p0kYsYepod
            04JPntOqS3NWUBypnd+VzQUmwdjz2MLBWOU11Kw/6Vm05+7JRgx3Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-28T12:01:46Z"
    mac: ENC[AES256_GCM,data:gnSHsr1+BPyF+Y8dWxoukHvED97mojH4wUNiKb/NN0I4raypr+p1b0fP4qogEbllsL5BwFhL0FoLnEwhecEoETXn0rGyV0QR7R/gJX4WnwpNY2S9K5QQINfhJCCLEK0RaxlcVc6vTEHKhphaUOE8hnYKUf8Z8XQdx+/7JdxDhr8=,iv:3LDKBNcQcHehfJBJ8oTfWvkz4MZMFeFuXUCIsIF9ClY=,tag:mBJNOKE/Ju3GaTSd5q3e1g==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
