#ENC[AES256_GCM,data:CE0IV5i6nmUWj0UP3zaqdd37CwxCfF2VDFA4N8oH9cjXMmloOleSxVaYz/yGKORt8zzhdblnxYyvjQ==,iv:tLJk/59M1CeOz2Mo8HjD7Je/D++ulOABkbmwi0+WCwI=,tag:TwBNVbJs2I31aXyo91K7uw==,type:comment]
apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    GE_MQTT_CLIENT_ID: ENC[AES256_GCM,data:odGpluJV9vjbZQm4907DjA==,iv:12CtFMjslxKsRWxW3XfWYpnIdNyFr3t5vFWGFyJukew=,tag:lzQGbv4IaPcgwKe09YCdyg==,type:str]
    GE_MQTT_USERNAME: ENC[AES256_GCM,data:BjxmbU1DVMsVYj8BJ20OONnhLKlSUg2O,iv:pLxXuc844KVyuH79dPwYQY5Lsix7RsKt8xSibsE4GZM=,tag:/589ohS6kQsFPtytJNBX6g==,type:str]
    GE_MQTT_PASSWORD: ENC[AES256_GCM,data:RPYgmdWpaQwca5BOVJQDjyxAjk70dBRN4ymX92pUq71zPQEnBCiM/cgP5vHj11wwecBle1vSOKUCja0BO6HEhKyS1BfaHwYsuZ+/9BG1f4PaOHDbcy3PtI0V7fFTQ8pX6MdJWS98qqw8/ZM/7pyA/PEJBl1nQMvZ6lhWfX/WbRH/UHim,iv:5TW1fTlfljDgm7tDFdaM5KyfTL2tiHPoEZlFSLp8Xo0=,tag:yy34t0ZNiddHkvJlO7sjrw==,type:str]
    GE_SERVER_DATABASE_USER: ENC[AES256_GCM,data:2LbitaVl5AjhHLFlOatWRSk2fecU89wxGsdaig==,iv:OceLdQBN5oxo/9+XoaetD6WMtvHPEGXjbh+Pa+A384c=,tag:x78Na1dOypSYzP+RUUXIqg==,type:str]
    GE_SERVER_DATABASE_PASSWORD: ENC[AES256_GCM,data:IW7IAP7t21VWUp2+JD+gTO0SOLXOlRc7NVmQ6pIsOFBLN1t+Rm+dL4wIhO8=,iv:K5QDdB9jEVZJyFdh1HYSRf0ljeyI2tiB/cnw7yivXOo=,tag:tkBvQ9FK9uZ2W1Y56fL1Ig==,type:str]
    GE_AUTH_OIDC_PROVIDER_BACKEND_CLIENT_SECRET: ENC[AES256_GCM,data:BMX8gvuMnTcX6/59iXHPjcbWHYVdOE+9QfT4nEHLxfwovOVi6uYG+XGiMOo=,iv:xI/wl614qwwyTtebRg0pDiTHTNIic2yB1QXavpLUXT4=,tag:05P6qT9knvj6H5h8H75LMw==,type:str]
    GE_AUTH_OIDC_PROVIDER_PUBLIC_KEY_STATIC: ENC[AES256_GCM,data:RPiuklZm/hHV7AsO6CN4cRvTAu4us+asto0CsvMaWGy2HrWn0u74S2J+y0HWzFshGUIkQnVkm3PPTdWBvwijR7I0n8t5tu0LV65HFaKxgPoxaMS2M43+i1gwncealbUScJvxQ5qZSo4frt6GINSAIc5O7XIUAoJnVVdqf2mFJjmgOITmFJYmhcZ6g5EL8LTceChj1D0TvPzfEbBdfHnYf5xl8T6OMB8kTO8ySV9+WxpD38w6iGbNmkRYGwf82cyS7MSvnAMocTKpZM2BeuZ8qRZMdgobvd8DmFETPa9mA5kdTPZPKXppGRmVMEYEovt3Q21CRtvw14tG3Sd1jH1v7Vks//vfxZ+Uz0vCJh8cJfCk8qsI4s/yyYSaR1dO+eH12xsMXLNDzBzcHE4+AGFbCCsxf0Tv1Zk3HOYBnGS1B3jB0qwYT5ddH+QKftX5/JYa0dHF5YvPlZgyeNYu+s/DK0ZEakDkFAnAlW2XnkIRQ7Xrq9Bc1EfxeEGTCrjq5RywhGbHk+6EGpRtYZepSwacYWLAbavAkf8vTG1wdEJR8UtMrKaLLMMogb7XkNu++FB7S2moxfOmYczIjLUkO3tv6+3kOXZYv/u43Gfgce/iSquHml52ksMzmG/Pb4CETzc5EAtODPYGQkkQJy0TvVT07wst7cBGg9+qocGbD/1ivQips5klTtVbYnB4aIg=,iv:Cpdjd2B6vz7l4W76Qi8IomPFEKt5/drfPR87BWwFKi4=,tag:BqRd+BIJMzQBTJQ0ARiy4w==,type:str]
    GE_AUTH_OIDC_PROVIDER_FRONTEND_CLIENT_SECRET: ENC[AES256_GCM,data:GgDoYpYkwSFPUjCFRlJaCK2tmVEZMQlkT0VWid2RcJrQA1jI7AXmZgNylT0=,iv:PstMdG01rXGUOdq2q9aL2L9/ym0NAX51ijBy2qjGPvc=,tag:MVZGjHRuTE3AXdx8Zod2nQ==,type:str]
    GE_S3_ROUTE-GPX_SECRETACCESSKEY: ENC[AES256_GCM,data:CN7KErLaE9KqPh5Gph/F/em773cbmFxU5sxvdcft4zIlIp8zk0dQ/rohLD8=,iv:B1euZ+J0paI8YZxSsokM3NNhjx5B8n8UZzrIu+duqq0=,tag:tgib+uUPyarLBq/TA++jqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ndzuf4g9ds5er8evh0xr8z8jtqkknyr9mrra0ajdv92puuyj532skgcel8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMWF4QVJpQ0lpVUpxRmpL
            bm03TDJlOGIwM25kZnRLclhkb0piTWZWb0RBCmxNejdYTnRlaDVqdFVsai8zZllT
            MnhLV3BseFJCSmNDSjg1VmdQT0NRV00KLS0tIExmVjNwQnNBWTYxSGY5VkxJa1dO
            bTdyYllrNTNZTjl2QlVpc2N1eGNmc2cK9GxRJB+6tqKMpHFtBp8J/OHU5d2haFEg
            El1LAeEtbB28LRj6Ia3E4gv9hyj0LGzBaz0Rizi9AEtUZgQDjuWF9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T19:40:27Z"
    mac: ENC[AES256_GCM,data:fwi1FGDDn/QbcY+vcI9OphKefzWgeRxWh3TX17IIiLiBZfOPrDqT64UDsooLvcvgElVOnmDt70CnTIJ4iy6sTTWPEa3oJ8SBKt6GX/pzz83V4YraB5EoSw4YlTNW52TFp9ynCpv6+KgotDAIH/CiiRly/IW5VicgTuS9vLyfdwY=,iv:mJ1yxy1jsRhk7PhmnFgQ9dwO7LvZaqTyiqRE+Xd+41M=,tag:0qPXMtpvztBdY9Khy3uQMw==,type:str]
    pgp: []
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.2
