name: "Notify on Reviewer Needed"
on:
  pull_request:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'need-reviewer' }}
    steps:
      - name: Notify on Discord
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "Pull request ${{ github.event.pull_request.html_url }} benötigt einen Reviewer"
          username: "GitHub Actions"
          avatar-url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
