name: "Update submodules"

on:
  repository_dispatch:
    types: [update-submodules]
  workflow_dispatch:

jobs:
  build-and-push-migrations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GREEN_ECOLUTION_PAT }}
          submodules: "true"

      - name: Update submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: git submodule update  --init --recursive --remote -f

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push postgres migrations
        uses: docker/build-push-action@v5
        with:
          context: .
          token: ${{ secrets.GREEN_ECOLUTION_PAT }}
          file: ./.docker/migrations/Dockerfile.postgres
          platforms: linux/amd64
          push: true
          tags: ghcr.io/green-ecolution/migrations-postgres:latest

  update-submodules:
    needs: build-and-push-migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GREEN_ECOLUTION_PAT }}
          submodules: "recursive"

      - name: "Setup yq"
        uses: dcarbone/install-yq-action@v1.1.1
        with:
          version: "v4.42.1"
          force: true

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Update submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: git submodule update  --init --recursive --remote -f

      - name: Get the latest commit hashes
        run: |
          COMMIT_SHA_BACKEND=$(cd green-ecolution-backend && git rev-parse --short HEAD)
          COMMIT_SHA_FRONTEND=$(cd green-ecolution-frontend && git rev-parse --short HEAD)
          echo "COMMIT_SHA_BACKEND=$COMMIT_SHA_BACKEND" >> $GITHUB_ENV
          echo "COMMIT_SHA_FRONTEND=$COMMIT_SHA_FRONTEND" >> $GITHUB_ENV

      - name: Dump frontend image tag
        run: |
          yq -i '.images[0].newTag="env(COMMIT_SHA_FRONTEND)"' ./deploy/kustomize/dev/kustomization.yaml

      - name: Dump backend image tag
        run: |
          yq -i '.images[1].newTag="env(COMMIT_SHA_BACKEND)"' ./deploy/kustomize/dev/kustomization.yaml

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: |
          git add green-ecolution-frontend green-ecolution-backend deploy/kustomize/dev/kustomization.yaml
          git commit -m "chore: update submodules and dump image tag" && git push origin develop || echo "No changes to commit"
