name: "Update submodules"

on:
  repository_dispatch:
    types: [update-submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GREEN_ECOLUTION_PAT }}
          submodules: 'recursive'

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Update submodules
        env:
          GITHUB_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: git submodule update  --init --recursive --remote -f

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GREEN_ECOLUTION_PAT }}
        run: |
          git add green-ecolution-frontend green-ecolution-backend 
          git commit -m "chore: update submodules" && git push origin develop || echo "No changes to commit"


